### ISSUE TITLE
cmake_minimum_version is set to quite high one.

### ISSUE THREAD

**Issue by kamiccolo** [ciplogic/fheroes2enh#10]
cmake_minimum_version is set to 3.8 and apparently, build itself works with even 3.5 and probably lower versions of CMake. I'd suggest keeping it as minimal as possible for Ubuntu <=16.04, etc users to be able to build the game itself without much of the hassle.

**Comment by ciplogic** [comment]
Thank you for feedback! I will update it. Also PRs are welcome 🗡
