### ISSUE TITLE
No install target

### ISSUE THREAD

**Issue by fenuks** [ciplogic/fheroes2enh#16]
Hello, I would like to write AUR package for Archlinux, alas there is no install target generated.

I am no cmake expert, but I added it, it required only few additional lines at the bottom of the `CMakeLists.txt` file.

```cmake
install(TARGETS fheroes2 DESTINATION bin)
if (LINUX)
    install(FILES fheroes2.desktop DESTINATION share/applications)
    install(FILES fheroes2.cfg DESTINATION share/${PROJECT_NAME}/data)
endif()
```
I could open merge request, but first I wanted to ask if you thought about renaming cmake's project name from `fheroes2` into, for example, `fheroes2-enh`? That would allow to have original `fheroes2` implementation installed alongside. And this repository lacks .desktop file and project icon, these would have to be added as well.

**Comment by ciplogic** [comment]
Hi @fenuks, you are correct: I think that we can change as you suggested with both changes: 
* cmake changes
* add as a separate install project name to be 'fheroes2enh'

**Comment by fenuks** [comment]
Hello, I've changed everything, but I think that perhaps `fheroes2-enh`, in terms of naming binaries, is better following convention commonly used, at least in Linux world. If you wish it to be `fheroes2enh`, then of course I will follow your request.

**Comment by ciplogic** [comment]
To me it is as good as being `fheroes2-enh`, if it matches Linux world.

**Comment by ciplogic** [comment]
No feedback for more than 6 months. Closing the issue...
