### ISSUE TITLE
Cursor moves very slowly

### ISSUE THREAD

**Issue by lucasw** [ciplogic/fheroes2enh#2]
I tried building this on a Ubuntu 16.04 system (a i7 laptop 2-3 years old) and when I run it the cursor lags behind the mouse a large amount and updates at a low frame rate.

Does building in release mode (`-DCMAKE_BUILD_TYPE=Release`) improve this?

If I can get pointed in the right direction I can possibly debug this myself.

Some other notes of possible interest are here https://gist.github.com/lucasw/d74c78f0d337b85ab22901c785b3c0c0#fheroes2

**Comment by ciplogic** [comment]
Hi Lucas!

So, first of all, I do build it on Fedora with CLion and in fact funnily enough runs on Linux of all my all three platforms.

Few things I can say upfront: as it is not my code I profiled a bit the code and it is "drawing starved" and this drawing it is done on CPU sadly for now.

So, first of all how to be able to play the game:
- **reduce screen resolution to a more low-end resolution**. I would say that 1024x768 should work. I have also an i7 with 4th generation and I see it running well enough. To change the resolution, you should edit 'fheroes2.cfg'.
- **compile on release mode**. Adding flags to GCC as `-flto` (you should add them both on linker and on compiler) should improve things. 

If you can reduce screen resolution and still things go too slow, I can add a page how to profile, but sadly you will see mostly blit code.

NB. As probably is written, it is not my original code, I wanted just to improve what I found in my honest view as a mess. I will love to improve in time things, but I cannot make an easy performance fix as I don't know .

I think over time are parts to improve and if you would want to invest improving performance, I know a part of code you can look into, but don't jump right away into "fixing big stuff" as it is harder that it seem.

**Comment by ciplogic** [comment]
Make sure you have in the folder you run the fheroes2.cfg file with this line added inside:
```
# video mode (640x480, 800x576, 1024x768, 1280x1024 or other divisible 32)
videomode = 1024x768
```

**Comment by ciplogic** [comment]
I tried the release build on Linux (I am having i7-4710HQ CPU @ 2.50GHz) and I can reproduce your behavior with a full screen 1920x1080) but it works ok (at least for my subjective eye) for 1280x1024 resolution (and lower one which I recommend it to you 1024x768).

**Comment by ciplogic** [comment]
May you say the state of the bug with a lower resolution?

Also, I've made a patch to remove few mouse events in between and it shouldn't lag too much. 

This reduced the perceived lag but it cannot fully fix it for many many reasons.

**Comment by ciplogic** [comment]
Does it behave now as you want? Or fixes are still required?

**Comment by ciplogic** [comment]
I reverted your commit as it has bad behaviors sometimes:
- if you switch between full screen and windowed mode, the events will start dissapear
- scroll mouse events will trigger for infinite number of times
