### ISSUE TITLE
Add CI pipeline to see current status of compilation

### ISSUE THREAD

**Issue by ihhub** [ciplogic/fheroes2enh#26]
It's unclear when new pull request breaks compilation of whole project moving such check to shoulders of author of this project. It's highly advisable to use some CI/CD platform. For example, for Windows compilation we can use [AppVeyor](https://www.appveyor.com/).

**Comment by ihhub** [comment]
This should be a first step to tackle compilation warning issues.

**Comment by ciplogic** [comment]
Sure, may you set it up if you have the experience? If you need more rights (including to make you as a committer), please let me know...
