### ISSUE TITLE
Fix override compilation warning

### ISSUE THREAD

**Issue by ihhub** [ciplogic/fheroes2enh#28]
While compiling on MacOS we see a lot of `overrides a member function but is not marked 'override' [-Winconsistent-missing-override]` warnings which is bad to have at first place as the project is not big.

**Comment by ciplogic** [comment]
I tried to reduce the overrides, but sometimes (as the code is not mine) the call is wrongly not an override, but a separate method. I remember around Army/Monster relation.

If you make a PR, make sure you don't regress the code.
