### ISSUE TITLE
Fheroes2 merge

### ISSUE THREAD

**Issue by Branikolog** [ciplogic/fheroes2enh#36]
Hi @ciplogic,

I see that your project is suspended. Will you consider merging it with another [fheroes2](https://github.com/ihhub/fheroes2) project? If the work is totally stopped would you mind to maybe give a link to that project so players would be happy to get an latest version of this cool game?

**Comment by ciplogic** [comment]
Yes, I will be glad to merge it. I will hopefully not forget to add a direct link to this repo. I am not sure if wanted, I can try to make PRs to move the enhanced code into new repo.

**Comment by Branikolog** [comment]
Hi @ciplogic,

It would be great if all cool changes from both projects will exist in one place but I'm not sure how you can do the merge if the above project has a lot of drastical changes and it wasn't inherited from your project. Adding a link would be great too! Fans of the Homm2 should enjoy the game on the highest level! :)
