### ISSUE TITLE
Add screenshots in the README

### ISSUE THREAD

**Issue by neuromancer** [ciplogic/fheroes2enh#5]
I think people will be more interested in testing this re-implementation and maybe collaborate with some code if you show the current state of this port.

**Comment by ciplogic** [comment]
Great advice!

**Comment by ciplogic** [comment]
Please close the task if you think the screenshots are representative. If you have a specific better screenshot, feel free to submit yours and I will replace mine.

**Comment by neuromancer** [comment]
They look great!
