### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by RobLoach** [ciplogic/fheroes2enh#6]
After building fheroes2, what is the intended directory structure suppose to look like?

**Comment by ciplogic** [comment]
Hi Rob.

I cannot give to you a straight answer, but I can help to clarify what is needed.

So. depending on platform (and on my CMake/Visual Studio experience), the FHeroes2Enh binary should be copied inside the root folder where are the sources.

But if you want your clean folder (or an original Heroes 2 folder), I recommend you to copy the following directories and files:
- in the game folder: FHeroes2Enh (`FHeroe2Enh.exe` on Windows), `fheroes2.cfg`  and `fheroes2.key`
- copy the folder: `files` (which contains the folders: fonts, images, lang, music, save, sounds, stats 
(the folder 'files' is submitted in GitHub here: https://github.com/ciplogic/fheroes2enh/tree/master/files )

If you are on Windows and you don't have SDL 1.2 libraries:
extract the `fh2dlls.zip` from here: https://github.com/ciplogic/fheroes2enh/tree/master/libs and extract it also to the root folder.

If you don't have Heroes 2 files, you can download the files from Heroes 2 Demo and extract them there:
https://github.com/ciplogic/fheroes2enh/releases/download/0.9.1/h2demo.zip

Another way to install it (on Windows) is to take the latest installer, and you will get a clean folder with all files, and you can copy the output folder into your place where you put the sources.

Installers are here:
https://github.com/ciplogic/fheroes2enh/releases

**Comment by ciplogic** [comment]
I hope it doesn't sound patronizing, but here is how to use the embedded installer (first minute and something from the clip):
https://www.youtube.com/watch?v=A8KwfSmW0G4&

**Comment by ciplogic** [comment]
Do you need more feedback? If it is enough for you, please close the issue.

**Comment by RobLoach** [comment]
Hmm, still getting the following...

```
01:31:22 PM: [ERROR]	SetLangEnvPath:  translation not found: en.po
terminate called after throwing an instance of 'Error::Exception'
[1]    26282 abort (core dumped)  ./fheroes2
```

en.po is in the root directoyr as well as lang.

**Comment by ciplogic** [comment]
May you copy the zip content from here into your folder?

https://github.com/ciplogic/fheroes2enh/blob/master/src/Installer/Installer/fh2enh.zip

**Comment by ciplogic** [comment]
So? 👍 

About the error, it is not related with "English language", the core-dump is not related with it.

May you say the OS or something to investigate on my end? May you run it with GDB or Clang and show to me a stack trace?

**Comment by ciplogic** [comment]
Not enough info even to look into... closing the issue.

**Comment by RobLoach** [comment]
Thanks! Did more testing with the demo content you sent, and continued to get that en.po error. Was likely a problem in my compilation process...

I'll recompile and try again and open up a new issue if I find something useful.

**Comment by ciplogic** [comment]
Maybe you can say to me which OS you are using so I can give you advice to see the issue.

As for "English error" the logic is a bit faulty there (it is from the times of the original FHeroes 2) as in fact it looks for "en.mo" instead of "en.po" file. But the "ERROR: ... " has no final effect in runtime (excluding it will not use "English translated" strings).

What I can recommend you, is that if you built FH2 using "debug configuration", is to call GDB against core dumps.

Simply call:
```
gdb FHeroes2Enh yourCoreFile
# and inside GDB
bt
```
And give the stack there...

Even more, I would recommend if you can use CLion, to run it under CLion, and it should give to you automatically the stack

https://stackoverflow.com/questions/5115613/core-dump-file-analysis

**Comment by kamiccolo** [comment]
mhm. Experiencing the same on Ubuntu 16.04. Copying lt.po to en.po only changed the error message.

**Comment by ciplogic** [comment]
As a partial fix, for users with directories that are not found, I will point them to download Heroes 2 Demo files locally.

https://github.com/ciplogic/fheroes2enh/commit/af8b88b662e38643d5441f112bd7e29b3cd1c9ff

@kamiccolo seems as a better fix?

**Comment by kamiccolo** [comment]
Okey, now the error makes more sense :} But I'd like to make it a little bit better. The thing is that resources in folders in capitals are from DOS version of the game. Which is perfectly legitimate ones and works well. So.... Either proper "importer" or case insensitive loader is required. Also, later I'm thinking to add an option while loading the game like `--resource-dir` or something. To be able to test out different mods or something.
