### ISSUE TITLE
Vampire Lord number of units during battle

### ISSUE THREAD

**Issue by progmetalbg** [ciplogic/fheroes2enh#9]
I tried fheroes2enh, played with Necromancers and in battles number of vampire lords changes a lot. For example I have 8 vampire lords, they hit 10 battle dwarves, and count of vampires goes down to 4 even before dwarves retaliate. At the end of the battle I don't lose vampire lords but still there is something wrong there.

**Comment by ciplogic** [comment]
May you attach a save file?

Or do you think that it is happening every time?

**Comment by progmetalbg** [comment]
It seems to happen on every map - attached Broken Alliance for example - you can attack the gargoyles and see the changes in the vampire lords stack.
[Broken_Alliance_009.zip](https://github.com/ciplogic/fheroes2enh/files/2119436/Broken_Alliance_009.zip)

**Comment by ciplogic** [comment]
Thank you! 

I hope I will get to the bottom of it, but very likely the fix will not be done right away (excluding is a trivial fix) in particular because I have family duties :) (aka: a newborn).

**Comment by ciplogic** [comment]
I think it was solved now, may you try to play it now and see if it is fixed?

https://github.com/ciplogic/fheroes2enh/releases/tag/1.0.0

**Comment by progmetalbg** [comment]
Yes, it seems fixed now.
Btw, I noticed that during battles, when you right click on a unit, no matter yours or enemy "Hit points left" is always 0. Should I open a new issue?

**Comment by ciplogic** [comment]
Please add it as a new bug. I will try to fix bugs one by one. This release was a lot of cleanup in code, so hopefully will be easier to fix.

**Comment by ciplogic** [comment]
Added new release fixing life reporting.

If it is not fixed, please open a new issue:

https://github.com/ciplogic/fheroes2enh/releases/tag/1.01
